# Generated by Django 3.2.12 on 2022-05-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_first_name', models.CharField(max_length=45, unique=True)),
                ('actor_last_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['actor_last_name', 'actor_first_name'],
            },
        ),
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('casting_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['movie', 'actor'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.AutoField(primary_key=True, serialize=False)),
                ('director_first_name', models.CharField(max_length=45, unique=True)),
                ('director_last_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['director_last_name', 'director_first_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['genre_name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_year', models.IntegerField(unique=True)),
                ('movie_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['movie_name', 'genre', 'movie_year'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['platform_name'],
            },
        ),
        migrations.CreateModel(
            name='Watching',
            fields=[
                ('watching_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watchings', to='movieinfo_app.movie')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='watchings', to='movieinfo_app.platform')),
            ],
            options={
                'ordering': ['movie', 'platform'],
            },
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(fields=('platform_name',), name='unique_platform'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movieinfo_app.director'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movieinfo_app.genre'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(fields=('genre_name',), name='unique_genre'),
        ),
        migrations.AddConstraint(
            model_name='director',
            constraint=models.UniqueConstraint(fields=('director_last_name', 'director_first_name'), name='unique_director'),
        ),
        migrations.AddField(
            model_name='casting',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='castings', to='movieinfo_app.actor'),
        ),
        migrations.AddField(
            model_name='casting',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='castings', to='movieinfo_app.movie'),
        ),
        migrations.AddConstraint(
            model_name='actor',
            constraint=models.UniqueConstraint(fields=('actor_last_name', 'actor_first_name'), name='unique_actor'),
        ),
        migrations.AddConstraint(
            model_name='watching',
            constraint=models.UniqueConstraint(fields=('movie', 'platform'), name='unique_watching'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('movie_year', 'movie_name', 'genre'), name='unique_movie'),
        ),
        migrations.AddConstraint(
            model_name='casting',
            constraint=models.UniqueConstraint(fields=('movie', 'actor'), name='unique_casting'),
        ),
    ]
